services:
  - type: web
    name: crypto-risk-ai
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        fromDatabase: false
      - key: GEMINI_API_KEY
        fromDatabase: false
      - key: DATABASE_URL
        fromDatabase: false
